# Generated by Django 3.0.6 on 2020-06-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200629_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('discount', models.FloatField(max_length=100)),
                ('customers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customers')),
            ],
        ),
    ]
